### ISSUE TITLE
#CalenDog Escrever README.md do projeto

### ISSUE THREAD

**Issue by AbraaoAlves** [dcTeam7/CalenDog#1]
## Description

Criado uma issue para cada checkbox desta issue

Descreva os seguintes topicos:

- [x] Pre-requisitos https://github.com/dcTeam7/CalenDog/issues/3
- [x] Descrição do projeto https://github.com/dcTeam7/CalenDog/issues/4
- [x] Rodando o projeto localmente https://github.com/dcTeam7/CalenDog/issues/6
- [x] Como fazer deploy https://github.com/dcTeam7/CalenDog/issues/7
- [x] Contribuidores https://github.com/dcTeam7/CalenDog/issues/8

**Comment by alanafilgueiras** [comment]
Eu estou escrevendo o read.me e aí estou tomando como exemplo o read.me do projeto [DOCUSAURUS](https://github.com/facebook/docusaurus#readme) se alguém tiver mais alguma sugestão pode deixar aqui :point_down:

**Comment by mikaelmonteirodev** [comment]
Fala @alanafilgueiras ! Na minha PR #23 _**(A qual marquei vc como revisora, 😄)**_  fiz uma pequena sugestão de tópicos para serem elencados no Readme. Se vc achar que são pertinentes podemos add ao projeto. Assim como as demais alterações.

**Comment by kevinDsousa** [comment]
Verifiquei aqui que todos os requesitos foram completados. @alanafilgueiras pode confirmar se ficou algo pendente? por favor!

**Comment by alanafilgueiras** [comment]
> Verifiquei aqui que todos os requesitos foram completados. @alanafilgueiras pode confirmar se ficou algo pendente? por favor!

Olá @KevinDik acabei de verificar o read.me e está tudo ok

**Comment by AbraaoAlves** [comment]
Parabéns galera!
Issue concluida com sucesso
